### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by andrewlangston** [jonahlipsky/jam-cloud#2]
Hey Jonah,

Good work here! A few notes from my end:

- [x] It may be helpful to store arrays of related resource ids within a given slice of state. For example, objects in the `albums` slice might include a key of `trackIds` pointing to an array of ids of tracks on a given album.
- [x] How will we keep track of genres and likes on the frontend?

As always, let me know if you have questions!

**Comment by jonahlipsky** [comment]
Thanks! I made a sample like and added the resources ids to the albums.

**Comment by andrewlangston** [comment]
Excellent, thanks for following up. Closing this issue.
