### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by andrewlangston** [jonahlipsky/jam-cloud#4]
Hey Jonah! Excellent work on your frontend routes. For the purpose of implementing the core features of Soundcloud, I have a few comments re: consolidation and reduction of routes for now:

- [ ] Let's remove the `/stream` and `/collection` routes for now. These would make fine bonus features, but should come only after implementation of song CRUD, continuous play, comments on songs, and user pages.
- [x] Feel free to simply the frontend route to user show pages. Something like `/users/:userId` will let us focus on functionality without too much headache over the exact path.

Let me know if you have any questions!

**Comment by jonahlipsky** [comment]
If you don't mind, I'd like to leave those routes as a reminder because of the way I broke down the components. I hear you that I won't need to execute them for a while.

**Comment by andrewlangston** [comment]
Not a problem. I'll close this issue now, but would suggest adding a reminder note to your wiki that these routes may feature in future implementations.
